address = "localhost:8118"
aht_20 = "AHT20 sensor"

[[outputs]]
name = "Output 1"
pin = 27

[[outputs.activations]]
when = "17:30:00"
for = "10 minutes"

[[outputs]]
name = "Output 2"
pin = 28

[[outputs.activations]]
when = "17:30:00"
for = "0.5 minutes"

[[outputs.activations]]
when = "18:30:00"
for = "1 hour 10 minutes 20 seconds"

[[outputs]]
name = "Output 3"
pin = 29

[[water_level_sensors]]
name = "Water level sensor"
echo_pin=18
trig_pin=17
max_distance=0.05
min_distance=0.20
